import './globals.css'
import { ReactElement, ReactNode } from 'react'
import { AppProps } from 'next/app'
import type { Metadata, NextPage } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'

const inter = Inter({ subsets: ['latin'] })

type NextPageWithLayout = NextPage & {
  getLayout?: ( page: ReactElement ) => ReactNode
} 

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout
}

export const metadata: Metadata = {
  title: 'Home - Martincito Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
